excludes:
  - \.gitignore
  - .*lock
  - \.git/.*
  - \.licensure\.yml
  - README.*
  - LICENSE.*
  - .*\.(md|rst|txt)

licenses:
  - files: any
    ident: AGPL-3.0
    authors:
      - name: FusionSuite Team
#    auto_template: true
    template: |
      Copyright (C) [year] [name of author]

      This program is free software: you can redistribute it and/or modify it
      under the terms of the GNU Affero General Public License as published by the Free Software Foundation, version 3.

      This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied
      warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Affero General Public License for more
      details. You should have received a copy of the GNU Affero General Public License along with this program. If not, see
      <https://www.gnu.org/licenses/>.


comments:
  - extensions:
      - rs
    commenter:
      type: line
      comment_char: "//"
      trailing_lines: 1
    columns: 80

